//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaPsicoaprende.AppDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumnos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumnos()
        {
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int Id { get; set; }
        public string cod_Alumno { get; set; }
        public string nom_Alumno { get; set; }
        public string ape_Alumno { get; set; }
        public System.DateTime fechaNac_Alumno { get; set; }
        public string nomResp_Alumno { get; set; }
        public string telfResp_Alumno { get; set; }
        public string colegio_Alumno { get; set; }
        public string gradoAcad_Alumno { get; set; }
        public string domicilio_Alumno { get; set; }
        public string evaluacion_Alumno { get; set; }
        public int DepartamentoId { get; set; }
        public int MunicipioId { get; set; }
        public int EstadoAlumnoId { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual EstadoAlumnos EstadoAlumnos { get; set; }
        public virtual Municipios Municipios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
