//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaPsicoaprende.AppDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trabajadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trabajadores()
        {
            this.Sesiones = new HashSet<Sesiones>();
        }
    
        public int Id { get; set; }
        public string cod_Trabajador { get; set; }
        public string nom_Trabajador { get; set; }
        public string ape_Trabajador { get; set; }
        public string domicilio_Trabajador { get; set; }
        public string telefono_Trabajador { get; set; }
        public int ProfesionId { get; set; }
        public int DepartamentoId { get; set; }
        public int MunicipioId { get; set; }
        public int EstadoTrabajadorId { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual EstadoTrabajadores EstadoTrabajadores { get; set; }
        public virtual Municipios Municipios { get; set; }
        public virtual Profesiones Profesiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sesiones> Sesiones { get; set; }
    }
}
